-- ============================================================================
-- BudgetManager — Fondations de l'accompagnant IA (Phase 5)
--   A) besoin/non-besoin : colonne is_essential sur les catégories
--   B) objectifs : table objectives (épargne ou plafond de dépense, daté/chiffré)
-- Ré-exécutable (IF [NOT] EXISTS / DROP IF EXISTS).
-- ============================================================================

-- ---- A) Catégories : essentiel vs superflu -------------------------------
alter table public.categories
    add column if not exists is_essential boolean not null default true;

-- Valeurs de départ raisonnables : le discrétionnaire par défaut = non essentiel
update public.categories set is_essential = false
    where name in ('Loisirs', 'Shopping') and category_type = 'EXPENSE';

-- ---- B) Objectifs (épargne / plafond de dépense) --------------------------
create table if not exists public.objectives (
    id            bigint generated by default as identity primary key,
    user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
    title         varchar(255) not null,
    -- SAVINGS = épargner un montant pour une date ; SPENDING_LIMIT = ne pas dépasser
    type          text not null check (type in ('SAVINGS', 'SPENDING_LIMIT')),
    target_amount numeric(15, 2) not null,
    target_date   date,
    -- Optionnel : objectif rattaché à une catégorie (ex. plafond « Loisirs »)
    category_id   bigint references public.categories(id) on delete set null,
    is_active     boolean not null default true,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now()
);
create index if not exists objectives_user_idx on public.objectives (user_id);

-- updated_at auto
drop trigger if exists trg_objectives_updated on public.objectives;
create trigger trg_objectives_updated before update on public.objectives
    for each row execute function public.set_updated_at();

-- RLS : propriétaire uniquement
alter table public.objectives enable row level security;
drop policy if exists owner_all on public.objectives;
create policy owner_all on public.objectives
    for all using (user_id = auth.uid()) with check (user_id = auth.uid());
